---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hyperledger-gql
    scrape-actuator: enabled
  name: hyperledger-gql
  namespace: kind
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: actuator
  selector:
    app: hyperledger-gql